name: Deployment Management Software 

on: [workflow_dispatch,push,pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:      
    
      - name: Installating podman 
        run: sudo apt update -y && sudo pip install podman-compose

      - name: Starting the build 
        run: sudo podman-compose up
      
      - name: Ngrok Config
        run: curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok;ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Configure Firewall
        run: sudo ufw allow 80/tcp
        
      - name: Starting Ngrok
        run: sudo ngrok http 80
